"""Service-report document builders.

DOCX is generated by filling the Simply Engineering letterhead template
(`doc_templates/service_report_base.docx`) — the letterhead table, fonts (Arial),
theme colours and footer come from that file, so output matches the SE template:
dark-blue (#1F3864) section headings and orange (#C45911) divider rules on the
invoice table.  PDF mirrors the same layout/colours via reportlab.
"""
import io
import os

from django.conf import settings

TAGLINE = 'Professional Security & Network Solutions'
PHOTO_MAX_W_MM = 75

BASE_DOCX = os.path.join(os.path.dirname(__file__), 'doc_templates', 'service_report_base.docx')

HEADING_BLUE = (0x1F, 0x38, 0x64)   # section headings
ORANGE_HEX = 'C45911'               # divider rules


def _bullets(points):
    return [str(p) for p in (points or []) if str(p).strip()]


def _fmt_qty(li):
    return f"{li.quantity:g} {li.unit}"


def _money(v):
    return f"$ {v:,.2f}"


def _heading_date(job):
    return job.invoice_date.strftime('%d %B %Y') if job.invoice_date else ''


def _photo_path(photo):
    try:
        path = photo.image.path
    except (ValueError, AttributeError):
        return None
    return path if path and os.path.exists(path) else None


# ── DOCX ────────────────────────────────────────────────────────────────────
def build_docx(job, tenant=None):
    from docx import Document
    from docx.shared import Pt, Mm, RGBColor
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document(BASE_DOCX)
    body = doc.element.body
    letterhead = doc.tables[0]

    # ── strip example body, keep letterhead table + section properties (footer) ──
    keep_tbl = letterhead._tbl
    for child in list(body):
        if child is keep_tbl or child.tag == qn('w:sectPr'):
            continue
        body.remove(child)

    # ── rewrite the "TO:" recipient cell (row 1) of the letterhead ──
    try:
        to_cell = letterhead.rows[1].cells[0]
        to_cell.text = ''
        to_cell.paragraphs[0].add_run('TO:').bold = True
        for line in (job.client.name if job.client else '', job.site_name, job.site_address):
            if line:
                to_cell.add_paragraph(str(line))
    except IndexError:
        pass

    # ── helpers ──
    def heading(text, size=11):
        p = doc.add_paragraph()
        r = p.add_run(text)
        r.bold = True
        r.font.size = Pt(size)
        r.font.color.rgb = RGBColor(*HEADING_BLUE)
        return p

    def label(text):
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(0)
        p.add_run(text).bold = True
        return p

    def bullet(text):
        p = doc.add_paragraph()
        p.paragraph_format.left_indent = Mm(8)
        p.paragraph_format.space_after = Pt(2)
        p.add_run('•  ' + text)
        return p

    def orange_rule(cell, *sides):
        tcPr = cell._tc.get_or_add_tcPr()
        tb = tcPr.find(qn('w:tcBorders'))
        if tb is None:
            tb = OxmlElement('w:tcBorders')
            tcPr.append(tb)
        for side in sides:
            old = tb.find(qn('w:' + side))
            if old is not None:
                tb.remove(old)
            el = OxmlElement('w:' + side)
            el.set(qn('w:val'), 'single')
            el.set(qn('w:sz'), '18')
            el.set(qn('w:space'), '0')
            el.set(qn('w:color'), ORANGE_HEX)
            tb.append(el)

    # ── report heading ──
    heading(f"Service Report – {job.service_number} | Date: {_heading_date(job)}")

    items = list(job.report_items.all())
    n_items = len(items)
    for idx, item in enumerate(items):
        prefix = f"Service Report {item.item_number} of {n_items} – " if n_items > 1 else "Service Report – "
        heading(prefix + item.title)
        for head, points in (('Issue:', item.issue_points),
                             ('Action Taken:', item.action_points),
                             ('Recommendation:', item.recommendation_points)):
            label(head)
            for b in _bullets(points):
                bullet(b)
        for photo in item.photos.all():
            path = _photo_path(photo)
            if not path:
                continue
            try:
                doc.add_paragraph().add_run().add_picture(path, width=Mm(PHOTO_MAX_W_MM))
            except Exception:
                continue
            if photo.caption:
                cap = doc.add_paragraph()
                cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
                cr = cap.add_run(photo.caption)
                cr.italic = True
                cr.font.size = Pt(8)
        if idx < n_items - 1:
            doc.add_page_break()

    # ── invoice table ──
    doc.add_paragraph()
    heading('Equipment, Labour & Materials')
    line_items = list(job.line_items.all())
    if line_items:
        tbl = doc.add_table(rows=1, cols=4)
        tbl.autofit = False
        widths = (Mm(14), Mm(110), Mm(22), Mm(28))
        hdr = tbl.rows[0].cells
        for i, txt in enumerate(('No.', 'Description of Works', 'Qty', 'Amount')):
            hdr[i].text = txt
            hdr[i].width = widths[i]
            hdr[i].paragraphs[0].runs[0].bold = True
            orange_rule(hdr[i], 'top', 'bottom')
        for li in line_items:
            c = tbl.add_row().cells
            vals = (str(li.line_number), li.description, _fmt_qty(li), _money(li.amount))
            for i, v in enumerate(vals):
                c[i].text = v
                c[i].width = widths[i]
        total = tbl.add_row().cells
        total[0].text = 'TOTAL'
        total[0].paragraphs[0].runs[0].bold = True
        total[3].text = f"S$ {job.total_amount:,.2f}"
        total[3].paragraphs[0].runs[0].bold = True
        for i, c in enumerate(total):
            c.width = widths[i]
            orange_rule(c, 'top')

    # ── remarks ──
    if job.remarks:
        doc.add_paragraph()
        label('Remarks:')
        for ln in job.remarks.splitlines():
            if ln.strip():
                doc.add_paragraph(ln)

    # ── signature / acknowledged by ──
    doc.add_paragraph()
    sig = doc.add_table(rows=1, cols=2)
    lc, rc = sig.rows[0].cells
    lc.paragraphs[0].add_run(tenant.signatory_name if tenant and tenant.signatory_name else '').bold = True
    if tenant and tenant.phone:
        lc.add_paragraph(f"Hp: {tenant.phone}")
    lc.add_paragraph(f"Date: {_heading_date(job)}")
    rc.paragraphs[0].add_run('Acknowledged By:').bold = True
    rc.add_paragraph('')
    rc.add_paragraph('Name & Designation')
    rc.add_paragraph('Date')

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


# ── PDF ─────────────────────────────────────────────────────────────────────
def _company_pdf(tenant):
    name = (tenant.name if tenant else None) or 'Simply Engineering'
    lines = []
    if tenant:
        if tenant.address:
            lines += [ln.strip() for ln in tenant.address.splitlines() if ln.strip()]
        if tenant.email:
            lines.append(f"E-Mail: {tenant.email}")
        if tenant.phone:
            lines.append(f"Tel: {tenant.phone}")
        if getattr(tenant, 'site_url', None):
            lines.append(f"Website: {tenant.site_url}")
    return name, lines


def _logo_path(tenant):
    if tenant and tenant.logo:
        path = os.path.join(settings.MEDIA_ROOT, str(tenant.logo))
        if os.path.exists(path):
            return path
    return None


def build_pdf(job, tenant=None):
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        ListFlowable, ListItem, Image as RLImage, PageBreak,
    )

    BLUE = colors.HexColor('#1F3864')
    ORANGE = colors.HexColor('#C45911')

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle('Tag', parent=styles['Normal'], fontName='Helvetica', fontSize=9, textColor=colors.grey))
    styles.add(ParagraphStyle('Addr', parent=styles['Normal'], fontName='Helvetica', fontSize=8, textColor=colors.HexColor('#555555')))
    styles.add(ParagraphStyle('Blue', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=11, textColor=BLUE, spaceBefore=8, spaceAfter=3))
    styles.add(ParagraphStyle('Label', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=10, spaceBefore=4, spaceAfter=1))
    styles.add(ParagraphStyle('Body', parent=styles['Normal'], fontName='Helvetica', fontSize=10))
    styles.add(ParagraphStyle('Caption', parent=styles['Normal'], fontName='Helvetica', fontSize=8, alignment=1, textColor=colors.grey))

    name, addr_lines = _company_pdf(tenant)
    items = list(job.report_items.all())
    n_items = len(items)
    story = []

    # ── header ──
    logo = _logo_path(tenant)
    left = []
    if logo:
        try:
            from PIL import Image as PILImage
            iw, ih = PILImage.open(logo).size
            w = 38 * mm
            left.append(RLImage(logo, width=w, height=w * ih / iw))
        except Exception:
            pass
    left.append(Paragraph('SERVICE REPORT / INVOICE', ParagraphStyle('t', fontName='Helvetica-Bold', fontSize=14, textColor=BLUE)))
    left.append(Paragraph(TAGLINE, styles['Tag']))
    right = [Paragraph(f"<b>{name}</b>", styles['Body'])] + [Paragraph(ln, styles['Addr']) for ln in addr_lines]
    header = Table([[left, right]], colWidths=[95 * mm, 80 * mm])
    header.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'TOP'),
                                ('LINEBELOW', (0, 0), (-1, -1), 1.5, ORANGE)]))
    story += [header, Spacer(1, 6)]

    to_lines = ['<b>TO:</b>']
    for line in (job.client.name if job.client else '', job.site_name, job.site_address):
        if line:
            to_lines.append(str(line))
    story.append(Paragraph('<br/>'.join(to_lines), styles['Body']))
    story.append(Paragraph(f"Service Report – {job.service_number} | Date: {_heading_date(job)}", styles['Blue']))

    # ── items ──
    for idx, item in enumerate(items):
        prefix = f"Service Report {item.item_number} of {n_items} – " if n_items > 1 else "Service Report – "
        story.append(Paragraph(prefix + item.title, styles['Blue']))
        for head, points in (('Issue:', item.issue_points),
                             ('Action Taken:', item.action_points),
                             ('Recommendation:', item.recommendation_points)):
            bullets = _bullets(points)
            story.append(Paragraph(head, styles['Label']))
            if bullets:
                story.append(ListFlowable([ListItem(Paragraph(b, styles['Body'])) for b in bullets],
                                          bulletType='bullet', start='•', leftIndent=14))
        for photo in item.photos.all():
            path = _photo_path(photo)
            if not path:
                continue
            try:
                from PIL import Image as PILImage
                iw, ih = PILImage.open(path).size
                w = PHOTO_MAX_W_MM * mm
                story += [Spacer(1, 4), RLImage(path, width=w, height=w * ih / iw)]
            except Exception:
                continue
            if photo.caption:
                story.append(Paragraph(photo.caption, styles['Caption']))
        if idx < n_items - 1:
            story.append(PageBreak())

    # ── invoice ──
    story.append(Paragraph('Equipment, Labour &amp; Materials', styles['Blue']))
    line_items = list(job.line_items.all())
    if line_items:
        data = [['No.', 'Description of Works', 'Qty', 'Amount']]
        for li in line_items:
            data.append([str(li.line_number), Paragraph(li.description, styles['Body']), _fmt_qty(li), _money(li.amount)])
        data.append(['TOTAL', '', '', f"S$ {job.total_amount:,.2f}"])
        tbl = Table(data, colWidths=[13 * mm, 112 * mm, 22 * mm, 28 * mm])
        tbl.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('ALIGN', (3, 1), (3, -1), 'RIGHT'),
            ('LINEABOVE', (0, 0), (-1, 0), 2.25, ORANGE),
            ('LINEBELOW', (0, 0), (-1, 0), 2.25, ORANGE),
            ('SPAN', (0, -1), (2, -1)),
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            ('LINEABOVE', (0, -1), (-1, -1), 2.25, ORANGE),
        ]))
        story += [tbl]

    if job.remarks:
        story.append(Paragraph('Remarks:', styles['Label']))
        for ln in job.remarks.splitlines():
            if ln.strip():
                story.append(Paragraph(ln, styles['Body']))

    story.append(Spacer(1, 14))
    sig_left = [Paragraph(f"<b>{tenant.signatory_name if tenant and tenant.signatory_name else ''}</b>", styles['Body'])]
    if tenant and tenant.phone:
        sig_left.append(Paragraph(f"Hp: {tenant.phone}", styles['Body']))
    sig_left.append(Paragraph(f"Date: {_heading_date(job)}", styles['Body']))
    sig_right = [Paragraph('<b>Acknowledged By:</b>', styles['Body']), Spacer(1, 24),
                 Paragraph('Name &amp; Designation', styles['Addr']), Paragraph('Date', styles['Addr'])]
    sig = Table([[sig_left, sig_right]], colWidths=[87 * mm, 88 * mm])
    sig.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'TOP')]))
    story.append(sig)

    buf = io.BytesIO()
    SimpleDocTemplate(buf, pagesize=A4, topMargin=15 * mm, bottomMargin=15 * mm,
                      leftMargin=15 * mm, rightMargin=15 * mm).build(story)
    buf.seek(0)
    return buf
