# Generated by Django 5.2.14 on 2026-06-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_task_start_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='weightage',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
