# Generated by Django 5.2.14 on 2026-06-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_task_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdocument',
            name='file',
            field=models.FileField(upload_to='tasks/documents/'),
        ),
        migrations.AlterField(
            model_name='taskphoto',
            name='photo',
            field=models.ImageField(upload_to='tasks/photos/'),
        ),
    ]
