# Generated by Django 5.2.14 on 2026-06-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_add_project_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='taskdocument',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='taskphoto',
            name='tenant',
        ),
    ]
