# Generated by Django 5.2.14 on 2026-06-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_project_tenant_remove_projectcomment_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='payment_received',
        ),
        migrations.RemoveField(
            model_name='project',
            name='quoted_amount',
        ),
    ]
