# Generated by Django 5.2.14 on 2026-06-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_quoted_amount_payment_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='expenses',
        ),
    ]
