# Generated by Django 5.2.14 on 2026-06-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_expenses_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('client', 'Client Project')], default='client', max_length=20),
        ),
    ]
