# Generated by Django 5.2.14 on 2026-06-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_add_issue_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
    ]
