# Generated by Django 5.2.14 on 2026-06-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_site_address_project_site_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
    ]
