# Generated by Django 5.2.14 on 2026-06-24 07:17

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_site_address_project_site_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('supervisor_count', models.PositiveIntegerField(default=0)),
                ('g_workers_count', models.PositiveIntegerField(default=0)),
                ('activity_short', models.CharField(blank=True, max_length=255)),
                ('activity_items', models.JSONField(blank=True, default=list)),
                ('personnel_names', models.JSONField(blank=True, default=list)),
                ('work_start', models.TimeField(blank=True, null=True)),
                ('work_end', models.TimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='daily_reports/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
