# Generated by Django 5.2.14 on 2026-06-24 08:31

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_daily_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WSHPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('photo', models.ImageField(upload_to='wsh/')),
                ('area', models.CharField(blank=True, max_length=255)),
                ('observation_type', models.CharField(choices=[('safe', 'Safe Condition'), ('unsafe', 'Unsafe Condition'), ('near_miss', 'Near Miss'), ('hazard', 'Hazard')], default='safe', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wsh_photos', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wsh_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
