# Generated by Django 5.2.14 on 2026-06-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_wsh_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wshphoto',
            name='observation_type',
            field=models.CharField(choices=[('safe', 'Safe Condition'), ('unsafe', 'Unsafe Condition'), ('near_miss', 'Near Miss'), ('hazard', 'Hazard'), ('daily_report', 'Daily Report')], default='safe', max_length=20),
        ),
    ]
