# Generated by Django 5.2.14 on 2026-07-30 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_wsh_photo_add_daily_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSHPhotoAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='wsh/')),
                ('wsh_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.wshphoto')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
