# Generated by Django 5.2.14 on 2026-06-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='position',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='site',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tenant',
        ),
    ]
