# Generated by Django 5.2.14 on 2026-06-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_remove_client_tenant_remove_company_tenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, help_text='Site / general address', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(blank=True, choices=[('mcst', 'MCST'), ('commercial', 'Commercial'), ('residential', 'Residential'), ('government', 'Government'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
