# Generated by Django 5.2.14 on 2026-07-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_rename_foremen_to_foreman'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nas_folder',
            field=models.CharField(blank=True, help_text='Customer folder name (YYYY-MM_Customer-Name) under the tenant base. Blank falls back to created-month + sanitized name. Overridable.', max_length=160),
        ),
        migrations.AddField(
            model_name='company',
            name='nas_folder',
            field=models.CharField(blank=True, help_text='Tenant base folder name under NAS_PROJECTS_ROOT. Blank falls back to a sanitized company name.', max_length=120),
        ),
    ]
