# Generated by Django 5.2.14 on 2026-07-30 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_client_nas_folder_company_nas_folder'),
        ('projects', '0025_wsh_photo_add_daily_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional — project this site was populated from / is linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='projects.project'),
        ),
    ]
