# Generated by Django 5.2.14 on 2026-07-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_site_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='radius',
            field=models.IntegerField(default=200, help_text='Geofence radius in metres (used for clock-in site matching)'),
        ),
    ]
