# Generated by Django 5.2.14 on 2026-06-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='wtsrequest',
            name='tenant',
        ),
    ]
