# Generated by Django 5.2.14 on 2026-06-21 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_asset_tenant_remove_inspection_tenant_and_more'),
        ('organisation', '0003_remove_client_tenant_remove_company_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('site_name', models.CharField(max_length=255)),
                ('site_address', models.TextField()),
                ('invoice_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('acknowledged_by', models.CharField(blank=True, max_length=255, null=True)),
                ('acknowledged_at', models.DateField(blank=True, null=True)),
                ('generated_doc_url', models.CharField(blank=True, max_length=500, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_jobs', to='organisation.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_jobs', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_jobs', to='organisation.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('lot', 'lot'), ('run', 'run'), ('pcs', 'pcs'), ('hrs', 'hrs'), ('set', 'set'), ('m', 'm')], default='lot', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='operations.servicejob')),
            ],
            options={
                'ordering': ['line_number'],
                'unique_together': {('job', 'line_number')},
            },
        ),
        migrations.CreateModel(
            name='ServiceReportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('issue_points', models.JSONField(default=list)),
                ('action_points', models.JSONField(default=list)),
                ('recommendation_points', models.JSONField(default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_items', to='operations.servicejob')),
            ],
            options={
                'ordering': ['item_number'],
                'unique_together': {('job', 'item_number')},
            },
        ),
    ]
