# Generated by Django 5.2.14 on 2026-06-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='tenant',
        ),
    ]
