# Generated by Django 5.2.14 on 2026-06-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_data_migrate_clients_to_organisation'),
        ('organisation', '0004_add_client_type_address_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='organisation.client'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organisation.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
