# Generated by Django 5.2.14 on 2026-05-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_deliveryorder_deliveryorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_no',
            field=models.CharField(blank=True, help_text='Linked project number e.g. AST-26-0001', max_length=20, null=True),
        ),
    ]
