# Generated by Django 5.2.14 on 2026-05-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_quotation_client_contact_quotation_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='do_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
