# Generated by Django 5.2.14 on 2026-06-13 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_deliveryorder_do_no_alter_invoice_invoice_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='project_no',
            field=models.CharField(blank=True, help_text='Linked project number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project_no',
            field=models.CharField(blank=True, help_text='Linked project number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='project_no',
            field=models.CharField(blank=True, help_text='Linked project number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='quotation',
            field=models.ForeignKey(blank=True, help_text='Set if payment is against a quotation (e.g. deposit) without an invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.quotation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Set if payment is against a specific invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.invoice'),
        ),
    ]
