# Generated by Django 5.2.14 on 2026-06-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_project_no_and_flexible_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='deliveryorderitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='tenant',
        ),
    ]
