# Generated by Django 5.2.14 on 2026-06-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_expense_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='title',
            field=models.CharField(blank=True, help_text='Quotation subject/title shown on the document', max_length=255, null=True),
        ),
    ]
