# Generated by Django 5.2.14 on 2026-06-30 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('direction', models.TextField(blank=True, default='')),
                ('objectives', models.TextField(blank=True, default='')),
                ('strategy', models.TextField(blank=True, default='')),
                ('tactics', models.TextField(blank=True, default='')),
                ('monitoring', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'company strategies',
            },
        ),
    ]
