# Generated by Django 5.2.14 on 2026-06-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='tenant',
        ),
    ]
