# Generated by Django 5.2.14 on 2026-06-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modules',
            field=models.JSONField(blank=True, default=list, help_text='List of module keys this user can access'),
        ),
    ]
