# Generated by Django 5.2.14 on 2026-06-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='schema_name',
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gst_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='modules',
            field=models.JSONField(blank=True, default=list, help_text='List of module keys enabled on this installation'),
        ),
    ]
