# Generated by Django 5.2.14 on 2026-06-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenant_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='site_url',
            field=models.CharField(blank=True, help_text='e.g. https://customer.sim-eng.com', max_length=255, null=True),
        ),
    ]
