# Generated by Django 5.2.14 on 2026-06-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='project_prefix',
            field=models.CharField(default='SE', help_text='Prefix for auto-generated project numbers, e.g. SE → SE-26-001', max_length=10),
        ),
    ]
