# Generated by Django 5.2.14 on 2026-06-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_tenant_uen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='files_url',
            field=models.CharField(blank=True, help_text='FileBrowser URL, e.g. https://files.astronic.com.sg/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST Registration Number — only if GST registered', max_length=50, null=True),
        ),
    ]
