# Generated by Django 5.2.14 on 2026-06-24 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_seed_permission_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_group',
            field=models.ForeignKey(blank=True, help_text='Custom permission group — overrides role defaults if set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.permissiongroup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('foreman', 'Foreman'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=20),
        ),
    ]
