# Generated by Django 5.2.14 on 2026-06-03 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_manager_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in_gps',
            field=models.JSONField(blank=True, help_text='GPS coords at clock-in: {"lat": x, "lng": y}', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/photos/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_gps',
            field=models.JSONField(blank=True, help_text='GPS coords at clock-out: {"lat": x, "lng": y}', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/photos/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_clock_in',
            field=models.BooleanField(default=False, help_text='Employee can use clock-in/out feature'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.employee', verbose_name='Supervisor'),
        ),
    ]
