# Generated by Django 5.2.14 on 2026-06-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_attendance_clock_in_gps_attendance_clock_in_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
