# Generated by Django 5.2.14 on 2026-06-03 08:23

import django.db.models.deletion
import shared.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hr', '0004_attendance_clock_in_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(), upload_to='attendance/photos/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out_photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(), upload_to='attendance/photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(), upload_to='staff/photos/'),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('location_name', models.CharField(max_length=200)),
                ('location_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('location_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius', models.IntegerField(default=200, help_text='Allowed clock-in radius in meters')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='hr.employee')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
