# Generated by Django 5.2.14 on 2026-06-09 07:16

import shared.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_singapore_public_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out_photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(), upload_to=''),
        ),
    ]
