# Generated by Django 5.2.14 on 2026-06-09 08:28

import shared.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_upload_to_filebrowser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(subfolder='attendance'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out_photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(subfolder='attendance'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(subfolder='database'), upload_to=''),
        ),
    ]
