# Generated by Django 5.2.14 on 2026-06-10 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_modules'),
        ('hr', '0009_manpower_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manpowersettings',
            options={'verbose_name': 'Manpower Settings', 'verbose_name_plural': 'Manpower Settings'},
        ),
        migrations.RemoveField(
            model_name='manpowersettings',
            name='show_directors',
        ),
        migrations.RemoveField(
            model_name='manpowersettings',
            name='show_helpers',
        ),
        migrations.RemoveField(
            model_name='manpowersettings',
            name='show_managers',
        ),
        migrations.RemoveField(
            model_name='manpowersettings',
            name='show_senior_supervisors',
        ),
        migrations.RemoveField(
            model_name='manpowersettings',
            name='show_supervisors',
        ),
        migrations.RemoveField(
            model_name='manpowersettings',
            name='show_technicians',
        ),
        migrations.RemoveField(
            model_name='manpowersettings',
            name='show_workers',
        ),
        migrations.AddField(
            model_name='manpowersettings',
            name='show_admin',
            field=models.BooleanField(default=True, help_text='Admin, Director'),
        ),
        migrations.AddField(
            model_name='manpowersettings',
            name='show_manager',
            field=models.BooleanField(default=True, help_text='Manager, Business Development, Advisor'),
        ),
        migrations.AddField(
            model_name='manpowersettings',
            name='show_superadmin',
            field=models.BooleanField(default=False, help_text='IT Developer'),
        ),
        migrations.AddField(
            model_name='manpowersettings',
            name='show_supervisor',
            field=models.BooleanField(default=True, help_text='Senior Supervisor, Foremen, Supervisor'),
        ),
        migrations.AddField(
            model_name='manpowersettings',
            name='show_worker',
            field=models.BooleanField(default=True, help_text='Construction Worker, Engineer, Project Engineer, Helper'),
        ),
        migrations.AlterField(
            model_name='manpowersettings',
            name='show_leave_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manpowersettings',
            name='show_on_site_indicator',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manpowersettings',
            name='show_teams',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manpowersettings',
            name='show_unassigned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manpowersettings',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant'),
        ),
    ]
