# Generated by Django 5.2.14 on 2026-06-12 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_project_prefix'),
        ('hr', '0010_simplify_manpower_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location_name', models.CharField(max_length=200)),
                ('location_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('location_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius', models.IntegerField(default=200, help_text='Clock-in radius in metres')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('days_of_week', models.JSONField(default=list, help_text='List of weekday ints 0=Mon … 6=Sun')),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='hr.employee')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
