# Generated by Django 5.2.14 on 2026-06-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_staff_deployment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='manpowersettings',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='staffdeployment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='tenant',
        ),
    ]
