# Generated by Django 5.2.14 on 2026-06-15 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_remove_attendance_tenant_remove_certification_tenant_and_more'),
        ('projects', '0019_add_project_to_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='projects.project'),
        ),
    ]
