# Generated by Django 5.2.14 on 2026-07-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_claim_claimitem_claimattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='health_declared',
            field=models.BooleanField(default=False, help_text='Employee declared themselves healthy at clock-in'),
        ),
    ]
