# Generated by Django 5.2.14 on 2026-07-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_attendance_health_declared'),
        ('hr', '0017_calendarevent'),
    ]

    operations = [
    ]
