# Generated by Django 5.2.14 on 2026-07-30 08:40

import shared.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_merge_20260730_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(randomize_filename=False, subfolder='attendance'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out_photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(randomize_filename=False, subfolder='attendance'), upload_to=''),
        ),
    ]
