# Generated by Django 5.2.14 on 2026-07-30 10:00

import shared.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_alter_attendance_clock_in_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='gps',
            field=models.JSONField(blank=True, help_text='GPS coords at time of report: {"lat": x, "lng": y}', null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=shared.storage.FileBrowserStorage(randomize_filename=False, subfolder='leave'), upload_to=''),
        ),
    ]
