# Generated by Django 5.2.14 on 2026-08-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_leaveapplication_address_leaveapplication_gps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimitem',
            name='remark',
            field=models.CharField(blank=True, help_text='Claimant note for this line item', max_length=255, null=True),
        ),
    ]
